//
// Generated by JTB 1.3.2
//

package timelinedata.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "Playback"
 * nodeToken1 -> "="
 * playbackChoice -> PlaybackChoice()
 */
public class Option implements Node {
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public PlaybackChoice playbackChoice;

   public Option(NodeToken n0, NodeToken n1, PlaybackChoice n2) {
      nodeToken = n0;
      nodeToken1 = n1;
      playbackChoice = n2;
   }

   public Option(PlaybackChoice n0) {
      nodeToken = new NodeToken("Playback");
      nodeToken1 = new NodeToken("=");
      playbackChoice = n0;
   }

   public void accept(timelinedata.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(timelinedata.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(timelinedata.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(timelinedata.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

