//
// Generated by JTB 1.3.2
//

package timelinedata.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "Variable"
 * identifier -> Identifier()
 * nodeList -> ( Vertex() )+
 */
public class Variable implements Node {
   public NodeToken nodeToken;
   public Identifier identifier;
   public NodeList nodeList;

   public Variable(NodeToken n0, Identifier n1, NodeList n2) {
      nodeToken = n0;
      identifier = n1;
      nodeList = n2;
   }

   public Variable(Identifier n0, NodeList n1) {
      nodeToken = new NodeToken("Variable");
      identifier = n0;
      nodeList = n1;
   }

   public void accept(timelinedata.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(timelinedata.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(timelinedata.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(timelinedata.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

