//
// Generated by JTB 1.3.2
//

package timelinedata.syntaxtree;

/**
 * Grammar production:
 * nodeList -> ( Option() )+
 */
public class OptionList implements Node {
   public NodeList nodeList;

   public OptionList(NodeList n0) {
      nodeList = n0;
   }

   public void accept(timelinedata.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(timelinedata.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(timelinedata.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(timelinedata.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

